### ISSUE TITLE
Lighthouse 성능 개선

### ISSUE THREAD

**Issue by HyungJun-Yoo** [ZeroBGG/zero-gg#105]
## 목적
> Lighthouse 성능 개선

## 작업 상세 내용
- [x] 성능 개선
- [x] 접근성 개선
- [x] 권장사항 개선
- [x] PWA 개선
- [x] 검색엔진 최적화 개선

### 개선 전
![Lighthouse 성능 개선](https://user-images.githubusercontent.com/70789958/226126118-cd3e0181-122a-4a89-b304-64c9f60415e0.png)

### 개선 후
![성능](https://user-images.githubusercontent.com/70789958/226454331-926829f8-7268-4f09-b4d2-6c39142517ba.png)

**Comment by oinochoe** [comment]
멋집니다 😄 성능 개선해서 초록색으로 모두 맞춰보세요.
