### ISSUE TITLE
Duo 컴포넌트 개발

### ISSUE THREAD

**Issue by Viiiin94** [ZeroBGG/zero-gg#18]
## 목적
> Duo 컴포넌트 개발
> 값을 입력하면 firestore에 저장
> firestore 수정 / 삭제 기능 추가
> 원하는 queue, tier, position을 선택해서 해당 데이터만 출력

## 작업 상세 내용
- [x] firestore 연동해서 duo찾기 기능 추가
- [x] 웹에서 직접 firestore 추가, 수정, 삭제 기능 추가
- [ ] 원하는 queue, tier, position 선택 및 출력
- [x] CSS 꾸며보기

**Comment by oinochoe** [comment]
매일 할 수 없는 상황인가보네요. 진행 상황이 조금 더 빠르면 좋겠습니다 : )

**Comment by Viiiin94** [comment]
> 매일 할 수 없는 상황인가보네요. 진행 상황이 조금 더 빠르면 좋겠습니다 : )

생각보다 다중 선택 필터를 적용하는데 시간이 걸리고 있습니다 최대한 빨리 방법을 찾아서 해결해보겠습니다!!
