### ISSUE TITLE
Header 컴포넌트 개발

### ISSUE THREAD

**Issue by HyungJun-Yoo** [ZeroBGG/zero-gg#3]
## 목적
> 페이지 이동을 위한 Header 컴포넌트 개발

## 작업 상세 내용
- [x] Header 컴포넌트 디자인
- [x] 페이지 이동 처리
- [x] index.tsx에 Header 컴포넌트 추가

**Comment by oinochoe** [comment]
서로 코드 보면서 해야되는 부분들은 vscode의 live share 사용해서 확인해주세요 😄
