### ISSUE TITLE
다중 멀티 필터 만들기

### ISSUE THREAD

**Issue by Viiiin94** [ZeroBGG/zero-gg#33]
## 목적
> 필터 별로 교집합을 만들어 원하는 조건의 Duo를 찾을 수 있게 해야합니다

## 작업 상세 내용
- [x] queue, tier, postion 별로 필터 만들기

## 현재 작업 내용
<img width="562" alt="스크린샷 2023-01-16 오후 4 20 21" src="https://user-images.githubusercontent.com/97148877/212619912-8a38ee0f-fe6c-4ed5-b7ca-f31eaad66597.png">

<img width="756" alt="스크린샷 2023-01-16 오후 4 20 35" src="https://user-images.githubusercontent.com/97148877/212619952-514a3ee8-b008-4764-9869-f8751fcd746b.png">

<img width="521" alt="스크린샷 2023-01-16 오후 4 20 46" src="https://user-images.githubusercontent.com/97148877/212619978-6850e6fe-9bc0-4b29-ad77-5a00be36b14d.png">

lolInfo에 저장된 리스트를 선택 값이 없으면 그대로 출력 
~~하지만 값을 선택해도 해당 value가 해당 key의 value값으로 들어가지 않습니다.~~ (해결완료)
하지만 다시 새로운 문제 발생!!!
<img width="521" alt="스크린샷 2023-01-17 오후 9 00 19" src="https://user-images.githubusercontent.com/97148877/212893649-62ccc189-8a67-4ef2-93d4-0f9cd69662ed.png">

타입을 해당 이름으로 만들게 아니라 [key: value] : string으로 바꿨더니 값이 들어감
~~하지만 해당 필터값을 클릭시 이전 값이 상태에 저장이 되버림;; 문제 해결이 필요해보임 ㅠㅠ~~
막상 웹페이지에서는 문제가 없었음, 다만 랜더링이 중첩이 되버리는데 이러한 과정을 줄일 필요가 있어보임

<img width="447" alt="스크린샷 2023-01-17 오후 9 02 47" src="https://user-images.githubusercontent.com/97148877/212894078-0558ed60-4754-40f4-9e2b-6f1526b30420.png">

## 참고 사항
https://velog.io/@parfaite73/Project1-7-%EA%B2%80%EC%83%89%ED%95%84%ED%84%B0-%EC%97%AC%EB%9F%AC%EA%B0%9C-%EC%A1%B0%EA%B1%B4%EC%9C%BC%EB%A1%9C-%EA%B2%80%EC%83%89%ED%95%98%EA%B8%B0-feat.-react-datepicker-Debounce

https://choonse.com/2022/04/25/1075/

**Comment by oinochoe** [comment]
reduce로 한방에 해결하는 방법이 좋아보이네요 😄

**Comment by Viiiin94** [comment]
> reduce로 한방에 해결하는 방법이 좋아보이네요 😄

꼭 성공해보겠습니다!!

**Comment by Viiiin94** [comment]
문제 해결 완료 렌더링을 줄일 필요가 있어보임
