### ISSUE TITLE
날짜별, 팀별 이중 필터 작업중

### ISSUE THREAD

**Issue by Yangs1s** [ZeroBGG/zero-gg#39]
## 목적
 날짜, 팀별로 필터링이 가능하게 기능구현
>## 작업 상세 내용

<img width="1775" alt="스크린샷 2023-01-14 오후 1 12 37" src="https://user-images.githubusercontent.com/92585734/212450114-66d7e590-4366-4a52-9e0e-aa455f08bb56.png">

- [x] 날짜별 필터 가능, but 날짜,팀별로 같이 필터링이 될수있게 작업하는중
- [x] 이중 필터를 위해서 일정 페이지 구조를 수정

### 진행사항 및 문제사항

- [x]  Data를 불러올때 쓰는 함수에서 파이어베이스에 있는 데이터를 담아오지 못하는 현상
- [x]  month값을 파라미터 값에서 useParams를 이용해서 빼왔지만 month를 바꾸는 순간부터 함수가 인식을 못해서 에러가 발생

### 해결 사항
- [x] Data를 불러오는 문제는 fetching을 할때 UseCallback을 useEffect로 바꾸고 읽어오기만 해서 async await부분을 제거하니 해결.
- [x] 자식에서 부모컴퍼넌트쪽으로 값을 받아 state값으로 저장함
![스크린샷 2023-01-23 오전 5 04 03](https://user-images.githubusercontent.com/92585734/213937704-5e7e514f-cdf1-47ea-bd27-cdc86b60b217.png)
- [ ] matches가 두경기 다 포함하고 있기에 조건문을 통해서 조금 유형별로 데이터가 표시되는 방법을 다르게 만들었습니다.

### 질문사항
- [ ] 리스트를 읽어오는 과정에서의 문제에서 이게 비동기의 문제인지를 잘 모르겠는데 혹시 읽어오는 과정에서의 비동기는 필요가 없는건가요?
- [ ] 제가 처음에 데이터를 읽어올떄 try - catch 구문이랑 asycn await 문을 동시에 사용한 상태였는데 이렇게 사용해도 괜찮은건지 

### 이 기능을 구현하면서 배웠던점
- reduce사용에 대해서 공부를 많이 하게 됐습니다.
- 팀별 조건을 줬을때, 처음엔 굉장히 복잡한 부분을 생각하게 됐는데
- 원리와 참고할만한 레퍼런스를 공부하고 나서 조건을 keyword로 간단하게 만들어보게 됐습니다.

### 참고 사항
https://velog.io/@parfaite73/Project1-7-%EA%B2%80%EC%83%89%ED%95%84%ED%84%B0-%EC%97%AC%EB%9F%AC%EA%B0%9C-%EC%A1%B0%EA%B1%B4%EC%9C%BC%EB%A1%9C-%EA%B2%80%EC%83%89%ED%95%98%EA%B8%B0-feat.-react-datepicker-Debounce

https://www.zerocho.com/category/JavaScript/post/5acafb05f24445001b8d796d

https://cpro95.tistory.com/689

**Comment by oinochoe** [comment]
1. 리스트를 읽어오는 과정에서의 문제에서 이게 비동기의 문제인지를 잘 모르겠는데 혹시 읽어오는 과정에서의 비동기는 필요가 없는건가요?
=> 서버 통신 뿐만 아니라 읽어오는 과정에서도 비동기는 필요합니다. 
```javascript
async 클라이언트 함수 () => {
  const 디비에서 가져오는 랭킹리스트 = await getRankingList(파라미터1, 파라미터2, 파라미터3);
  if (디비에서 가져오는 랭킹리스트) {
    랭킹리스트 변경([...랭킹리스트_정보]);
  }
}
```

 제가 처음에 데이터를 읽어올떄 try - catch 구문이랑 asycn await 문을 동시에 사용한 상태였는데 이렇게 사용해도 괜찮은건지
=> 맞습니다. try catch도 필요하고 async await를 사용하는 부분도 둘 다 사용해야 합니다.

@Yangs1s
