### ISSUE TITLE
Duo 페이지 : 무한스크롤, 인풋렌더링 영역

### ISSUE THREAD

**Issue by Viiiin94** [ZeroBGG/zero-gg#43]
## 목적
> 버튼을 클릭시 인피니트스크롤을 할지 그냥 자동스크롤로 인피니트스크롤을 만들지 고민
> input 렌더링이 input영역이 아닌 form 영역 전체가 되는데 이러한 문제점을 어떻게 해결할지 고민

## 작업 상세 내용
- [x] 인피니티 스크롤
- [x] input 렌더링 영역 수정

https://user-images.githubusercontent.com/97148877/214517867-c45e9524-c532-4129-9df1-ceb0f6b05afb.mov

## 참고 사항
https://mingeesuh.tistory.com/entry/Firebase-%ED%8C%8C%EC%9D%B4%EC%96%B4%EC%8A%A4%ED%86%A0%EC%96%B4-%ED%8E%98%EC%9D%B4%EC%A7%80%EB%84%A4%EC%9D%B4%EC%85%98-%EB%AC%B4%ED%95%9C-%EC%8A%A4%ED%81%AC%EB%A1%A4-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0

**Comment by oinochoe** [comment]
버튼 클릭하는 infinite scroll 방식은 주로 섬네일들이 여러 컬럼으로 있는 경우 많이 사용되고, 스크롤 방식은 한 줄로 긴 기사글 등에 자주 사용됩니다 😄 성질에 따라서 판단하고 ux적으로 어떤게 더 편할지 고민해보세요.

**Comment by oinochoe** [comment]
input 영역에 대한 공통 컴포넌트가 있으면 해결 됩니다. <Input /> 과 같이 사용할 수 있는 공통 컴포넌트를 만들고 필요시 memo 컴포넌트도 하세요.

**Comment by Viiiin94** [comment]
> input 영역에 대한 공통 컴포넌트가 있으면 해결 됩니다. 과 같이 사용할 수 있는 공통 컴포넌트를 만들고 필요시 memo 컴포넌트도 하세요.

답변 감사합니다 멘토님!! 어제 input의 공통 컴포넌트를 만들어서 진행을 해봤는데 렌더링 되는 부분이 input영역을 포함해서 form 영역도 렌더링 되고 뿐만아니라 공용으로 만들어진 input 전체가 렌더링이 됩니다. 예를 들면, id를 입력하면 password도 렌더링이 됩니다... 혹시 input 컴포넌트를 만들 때 form영역 포함해서 컴포넌트를 만들어야 하는지 아니면 다른 방법이 있는지 질문드립니다.

**Comment by Viiiin94** [comment]
memo를 사용하니깐 해당 영역만 렌더링이 됐습니다!! memo를 안해봤는데 했다고 착각해서 글을 썼네요 죄송합니다!! ㅠㅠ
그리고 radio도 컴포넌츠를 했고 memo도 사용해봤는데 전체 영역이 컴포넌츠가 되어서 오마주한 해당 사이트 duo.op.gg/lol 를 프로파일 해봤는데 전체 영역이 렌더링되는건 같아서 진행해도 될 것 같습니다!!

**Comment by oinochoe** [comment]
맞습니다 레디오는 여러개중에 하나를 선택하는 것이기 때문에 전체 영역이 렌더링될 수 있습니다 @BTSBRINGMEHERE

**Comment by Viiiin94** [comment]
버튼 형식 infinite scroll 개발 완료
몇 번의 테스트 진행 후 재수정 필
