### ISSUE TITLE
Duo page 미디어쿼리 작업 / pwa 알아보기

### ISSUE THREAD

**Issue by Viiiin94** [ZeroBGG/zero-gg#51]
## 목적
> 반응형 웹을 위한 미디어 쿼리, 리드미 수정

## 작업 상세 내용
- [x] Duo page 미디어쿼리 작업 ~~(절반 완성)~~

## 참고 사항
-미디어쿼리
https://ossam5.tistory.com/308
https://velog.io/@kskim625/CSS-%EB%AF%B8%EB%94%94%EC%96%B4-%EC%BF%BC%EB%A6%AC-%EB%B0%98%EC%9D%91%ED%98%95-%ED%8E%98%EC%9D%B4%EC%A7%80

-pwa
https://www.saichoiblog.com/react-pwa/
https://github.com/vercel/next.js/issues/30692
https://velog.io/@boorook/Vite-React-TypeScript-PWA-%EB%A7%8C%EB%93%A4%EA%B8%B0-AWS-Amplify-%EB%B0%B0%ED%8F%AC

-리드미
- [ ]  **최종 구현 화면 이미지 / 동영상으로 제공**
    - 화면을 어떤 구조로 구성했는지에 대한 설명
    - 라우트나 기능별로 구분하여 제공하면 좋습니다 👍
- [ ]  **설치, 환경설정 및 실행 방법**
    - 프로젝트 실행 시 필요한 환경 세팅 확인 (script, port, env, …)
- [ ]  **구현 요구 사항 목록**
    - 체크 리스트 형태로 추가
- [ ]  **사용한 프레임워크 및 라이브러리 설명**
    - package.json 참조하여 선택한 이유 작성
- [ ]  **폴더 구조 설명**
    - 폴더를 구분한 기준에 대하여 설명
    - tree 명령어를 사용하면 간편하게 디렉토리 구조를 출력할 수 있음
- [ ]  **과제 진행 시 주안점 작성**
    - 고민한 부분에 대하여 서술
- [ ]  **한계점 및 개선 사항 작성**
    - 고려는 하였으나 실제 구현하지 못한 부분에 대하여 서술

## 질문사항

**Comment by Yangs1s** [comment]
https://web.dev/progressive-web-apps/  여기도 참고하시면 좋을거 같아요

**Comment by Viiiin94** [comment]
공식 홈페이지가 있었네요~! 감사합니다! 
@Yangs1s

**Comment by oinochoe** [comment]
오 pwa하실 때 push 기능도 한 번 구현해보세요 ^^ @BTSBRINGMEHERE
