### ISSUE TITLE
vite 환경 pwa

### ISSUE THREAD

**Issue by Viiiin94** [ZeroBGG/zero-gg#68]
## 목적
> 기존의 firebase를 통해서 pwa push기능을 추가하고 싶었지만 vite, typescript의 조합으로는 도저히 방도가 없어서 다른 형태로 제작해보기

## 작업 상세 내용
- [x] vite환경 pwa 제작
- [x] Duo 컴포넌트 버그 수정

## 참고 사항
https://web.dev/i18n/ko/progressive-web-apps/
https://velog.io/@boorook/Vite-React-TypeScript-PWA-%EB%A7%8C%EB%93%A4%EA%B8%B0-AWS-Amplify-%EB%B0%B0%ED%8F%AC

## 작업에 필요한 플러그인
```
~~npm i vite-plugin-pwa -D ~~
```
플러그인을 사용하지 않고 진행할 예정입니다.
### 현재 키 에러가 일어나는 부분입니다.
<img width="1440" alt="스크린샷 2023-01-31 오후 2 18 14" src="https://user-images.githubusercontent.com/97148877/215672340-95491734-6368-4afa-8dd5-046139a98788.png">
<img width="772" alt="스크린샷 2023-01-31 오후 2 19 57" src="https://user-images.githubusercontent.com/97148877/215672384-5b3925e5-b708-4181-8282-18bb67f1d377.png">
<img width="1140" alt="스크린샷 2023-01-31 오후 2 31 26" src="https://user-images.githubusercontent.com/97148877/215674285-6b037914-7a62-499a-be43-e3294e760ebd.png">

- 처음에는 키 에러가 JSX로 마크업되는 부분에서 일어나는 줄 알았는데 확인해보니깐 firestore에 저장된 데이터를 불러오는 과정에서 해당 딕셔너리를 저장할 때 일어나는 문제인 것 같습니다. 유니크한 key값의 문제라서 동작에는 문제가 없습니다.
- list로 해당 컴포넌트나 마크업에서는 유니크한 key를 전달해 주고있습니다...

**Comment by oinochoe** [comment]
@BTSBRINGMEHERE 해당 에러는 KEY에러가 맞고 FIRESTORE랑 관련이 없는 듯 하네요.

```JSX
// Duo
{lolInfoFilterList.length !== 0 ? (
  lolInfoFilterList.map((item: DuoType, idx: number) => {
    const UNIQUE_KEY = item.userId + item.createdAt + idx.toString();
    if (item.position && item.queue && item.tier !== null) {
      return (
        <div key={idx}>
          <DuoCards key={UNIQUE_KEY} duoObj={item} />
        </div>
      );
    }
  })
```


```JSX
// DuoCards
const DuoCards = ({ duoObj }: { duoObj: DuoType }) => {
  const UNIQUE_KEY = duoObj.userId + duoObj.timeSet;
  const lane = positions.map((item, idx) => {
    if (item.lane === duoObj.position) {
      return (
        <div key={idx}>
          <img src={`${LANE_ICONS_URL}/${item.url}`} />
        </div>
      );
    }
  });

  const ti = tiers.map((item, idx) => {
    if (item.tier === duoObj.tier) {
      return (
        <div key={idx}>
          <img src={`${TIER_IMG_URL}/${item.url}`} />
        </div>
      );
    }
  });

```

**Comment by Viiiin94** [comment]
감사합니다 ㅠㅠ 해결했습니다. !!
지금 이름이 생각이 안나는데 빈 <></> 로 감싸줄때랑 
div로 감싸줄 때 차이점이 있을까요??? @oinochoe

**Comment by oinochoe** [comment]
@BTSBRINGMEHERE 좋은 질문 입니다 내부적으로 fragment 엘리먼트는 fragment 생성 후에 appendchild한 후에 버려집니다.
태그로 직접 감싸면, createElemnet로 엘리먼트를 실제로 생성하고 그 내부에 appendchild를 하게 됩니다 😀 

따라서 img태그만 필요하다면 key를 img태그에만 주셔도 무방합니다.

**Comment by Viiiin94** [comment]
감사합니다 멘토님!! 사실 fragment를 사용하면서 단 한번의 고민도 없이 계속 사용해와서 이러한 문제점을 파악하지 못했습니다....
key값을 그냥 원하는 마크업에만 주면 될 줄 알았는데 생각보다 세심하게 작동하네요 !! @oinochoe
